const PATH = {
    EVENT: "event",
    DASHBOARD: "dashboard",
    SEEK:"seek",
    FACE:"face",
    LICENSE_PLATE:"license plate",
    SIGNIN:"signin",
    ADD_PROFILE:"/profile/new/",
    PROFILE:"profile",
    PROFILE_INFO:"profile/info/:id",
    PROFILE_EDIT:"profile/edit/:id",
    LIST:"list",
    NOTIFICATION:"notification",
    NOTIFICATION_DETAIL:"notification/:id",
    PLATE:"plate",
    NEW_PLATE:"/plate/new/",
    PLATE_DETAIL:"/plate/view/:id",
    PLATE_UPDATE: "/plate/update/:id",
    BLACK_LIST: "black_list",
    BLACK_LIST_UPDATE: "/black_list/update/:id",
    BLACK_LIST_VIEW: "/black_list/view/:id",
    NEW_BLACKLIST: "/black_list/new/",
    SEARCH: "/search",
    SEARCH_PLATE: "/search/plate",
    CAMERA: "/camera",
    WEBPUSH: "/webpush",
    ERROR: "/error"
}
export default PATH;
